---
- name: Update sources
  apt: update_cache=true cache_valid_time=86400
  changed_when: false

- name: Install apt-cacher-ng
  apt:
    name: apt-cacher-ng
    default_release: "{{ apt_cacher_ng_default_release|default(omit) }}"
    state: present
